### ISSUE TITLE
What is the actual purpose of this library? 

### ISSUE THREAD

**Issue by Hakuz** [Albert-Gao/micro-aws-lambda#2]
It might sound noob but what is the actual purpose of this library?  Is this the small library that let you write the lambda function using typescript? If yes can you rewrite some AWS provided javascript lambda function using this library.

**Comment by Albert-Gao** [comment]
Hi, thanks for your attention.

Just like any other middleware mechanism, middleware is for decoupling your logic.

Lambda is a pretty good platform, for simplifying your infrastructure,
but it won't result in better code.

With middleware, your business logic can be decoupled, well tested and reused in other functions.
So, in a very ideal world, when you decouple your atomic action, you can compose a future endpoint lambda without writing code, you still need to write the integration test, but each piece is already well tested. Which will make it easy enough for you.

For example.

```typescript
const myHandler = lambdaWrapper({
    beforeHooks: [validateBodyWithSchema(UserSchema), isCompanyExist, isPaymentInfoValid],
    handler: justGrabInfoFromDBAndReturn,
    afterHooks:[discardFields(['password', 'address']), combineUserName]
});
```

In the `beforeHooks` :
I `validateBodyWithSchema`, then verify the company info and payment info, 

after that, in the handler, I simply just return the user from db,

In the `afterHooks`:
I discard confidential fields, and combine the user names.

This is just an example to show you how to use middleware to decouple your logic.

As you can see, you can use it to compose your logic.

The beautiful of `micro-aws-lambda` is it adds nearly no overheads to your overall bundle, but still able to give you a feature-rich middleware system you can use to compose your business logic.

Hope it helps, thanks :)

**Comment by Hakuz** [comment]
Thanks Gao that was helpful. So let's say my lambda needs to authenticate with the RESTServer before fetching the data and send the count of records to the websocket for notification purpose. So basically the authenticate part will be in the beforeHooks, datafetch in the handler and sending the notification based on the availability of count goes to afterHooks.

**Comment by Albert-Gao** [comment]
Yes, you get it right, try to adopt the ancient rule: `one job per function`, and enjoying the composing ability it enables. :) You will be surprised at how much code you can reuse later.

People are probably already doing that anyway. :) But `micro-aws-lambda` will make it easier, because of its declarative nature.

**Comment by Albert-Gao** [comment]
Will close it for now, feel free to re-open it if you still have questions.

Reminder: v3 just released with a new simpler interface.
