### ISSUE TITLE
Promises on middlewares

### ISSUE THREAD

**Issue by yocmen** [Albert-Gao/micro-aws-lambda#4]
Hi, I wonder how can I manage promises on the middlewares functions, I'm working with redis and mysql, in 1 middleware I check if a value exists in Redis, if it's there I need to return the value, if not then I can pass to the other function/middleware where I will fetch data from mysql, then cache it on Redis then return the results, but I'm having troubles to make this whit this flow, can you give me a hint please, thanks in advance.

Is ok to `throw success({ body: JSON.stringify(data) });` to stop the chain of middlewares and just return data?

**Comment by Albert-Gao** [comment]
yes, if you just throw, it will stop the chain, return what you throwed

if you throw a `success()`, `success` will be returned

**Comment by yocmen** [comment]
Really thanks for the answer.
